image: debian:latest

variables:
  DEBIAN_FRONTEND: noninteractive
  BUILD_FOLDER_NAME: $CI_PROJECT_DIR/packages

before_script:
  - apt-get -qq update > /dev/null 2>&1
  - apt-get -qq install -y curl > /dev/null 2>&1
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get -qq install -y nodejs autoconf automake build-essential gcc g++ make rpm > /dev/null 2>&1
  - npm install

release:
  only:
    - master
  script:
    - npm run pack:prod
    - mkdir $BUILD_FOLDER_NAME
    - mv ./output/build/*.* $BUILD_FOLDER_NAME/
  artifacts:
    name: fan-control-${CI_COMMIT_REF_SLUG}
    when: on_success
    paths:
      - '*.AppImage'
      - '*.snap'
      - '*.tar.gz'
      - '*.deb'
      - '*.rpm'